require("user.options")
require("user.plugins")
-- require("user.packer")
require("user.usability")
require("user.theme")
require("user.interface")
require("user.pretty_fold")
require("user.telescope")
require("user.keymaps")
require("user.cmp")
require("user.lsp")
require("user.template")
require("user.toggleterm")
-- -- require("user.gitsigns")
require("user.marks")
require("user.netrw")
require("user.harpoon")
